### ISSUE TITLE
nalgebra examples

### ISSUE THREAD

**Issue by zicklag** [smartcorelib/smartcore-examples#3]
It would be great to have at least one simple example, like maybe the iris dataset one from the website's Getting Started section, that demonstrated how to load the data using NAlgebra.

**Comment by VolodymyrOrlov** [comment]
Hi @zicklag. I didn't realize we don't have a good example where I use `nalgebra` matrices to fit a simple ML algorithm to some data, thanks for pointing it out!

I've just submitted a PR with such an example: https://github.com/smartcorelib/smartcore-examples/pull/4
